baseurl: "https://shreyas.ragavan.cc/"
title: "Eudaimonia"
theme: "zen"
languageCode: ""       # Set your language code (only needed for none multilingual sites).

params:
  alpine: false              # Add AlpineJS, default false.
  author: 
    name: Shreyas Ragavan                  # Your Name
    url:                    # https://example.org/somepage
    avatar:                 # path/to/some-image.jpg
  blogSections:             # Sections whose <schema.org> `JSON+LD` in the page `<head>`
    - post                  # will be `@type: BlogPosting`.
    - ""                 # Defaults to a list including only 'post' and 'blog'.
  breadcrumbSections:       # Sections in which pages will have a `BreadcrumbListing`
    - post                  # in the <schema.org> `JSON+LD` in the page's `<head>`.
    - projects              # This theme requires Hugo `v0.109.0` or higher to
                             # generate the `BreadcrumbListing`.
  cookieConsent: true       # Show cookie consent form, default false.
  contact: "sr@eml.cc"
  dateformat: ""            # Set the date format, default to "2 January, 2006"
  description: "Personal website and blog"           # Set site description, used in meta tags and JSON-LD
  favicon: "favicon.ico"    # Relative path to favicon in json feed, no leading slash.
  feedlinks: true           # Show feed links in the footer.
  footer: "License"
  icon: "favicon-32x32.png" # Relative path to icon in json feed and JSON-LD, no leading slash.
  image: ""                 # Relative path to site image in JSON-LD, no leading slash.
  imageMaxWidth: ""         # Max width for images added via figure shortcode.
  internalPagination: true  # Use Hugos internal pagination template, default false.
  jquery: false              # Add jQuery, default false.
  languageDir: ""           # Set ltr or rtl, defaults to ltr.
  logo: false               # Turn off the logo, defaults to true.
  logoPath: img/SR-reduced.jpeg                 # Relative path to site logo, defaults to "images/logo.png", no leading slash.
  logoHeight:                # Set logo height, defaults to none.
  logoWidth: 150px                # Set logo width, defaults to none.
  mainSections:             # The sections you want to have listed on the front page.
    - ""            # Default to the section with most content if not set.
    - ""            # Set to empty if no section should be listed.
  math: false                # Turn on math typesetting with KaTeX, default false.
  menuInHeader: true        # Move the main menu to the header, default false.
  microUsername: ""         # Your micro.blog username.
  mobileMenu: false          # Turn on a mobile menu on small screens, default false.
  mobileMenuOutline: false   # Mobil menu button as outline, default false.
  piwikSiteId:              # Matomo site id
  piwikTrackerUrl: ""       # Matomo url, schemaless and no slash on end (example.org/matomo).
  plausibleSiteID: ""       # Plausible site id/domain.
  plausibleTrackerURL: ""   # Plausible url, schemaless and no slash on end. Optional, defaults to "plausible.io/…"
  poweredby: true           # Show powered by hugo in footer
  privacyPolicyUrl: ""      # If set will add link to cookie consent form.
  relatedposts: true        # Show related posts under a "See also" section, default false.
  sassTranspiler: "libsass" # The Sass transpiler to use, default "libsass".
  searchLimit: 500           # Max number of search hits, default 20.
  sidebar: false             # Show a sidebar to the right, default false.
  siteName: True             # Hide the site name (visually-hidden), default true.
  submitted: false           # Show author and date information for a post.
  themeColor: "#e73555"      # Hex color value, used in meta tags, default "#ffffff".
  umbrella: false            # Add Umbrella JS, default false.
  lastmod : ["lastmod", ":git", "date", "publishDate"]

outputFormats:
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

outputs:
  home: ["HTML", "SearchIndex", "JSON", "RSS"]

markup:
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: false
    style: "github"
    tabWidth: 4

taxonomies:
  tag: "tags"



# menu:
#   main:
#     - name: "Random page"
#       identifier: "random"
#       weight: 40
