---
title: "Hugo Zen theme"
baseURL: "https://example.org/"
theme: "hugo-theme-zen"
languageCode: "en-GB"
defaultContentLanguage: "en"
pluralizelisttitles: false
removePathAccents: true
paginate: 5
paginatePath: "page"
rssLimit: 20
author:
  name: "Your Name"
  url: "https://example.org/somepage"
  avatar: "path/to/some-image.jpg"

outputFormats:
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

outputs:
  home: ["HTML","RSS", "JSON", "SearchIndex"]
  section: ["HTML","RSS", "JSON"]
  projects: ["HTML","RSS", "JSON"]

permalinks:
  blog : "/:slug/"
  tags : "/blog/:slug"
  notes : "/:slug/"

params:
  contact: "shreyas@fastmail.com"
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  description: "The zen theme for Hugo example site."
  dateformat: "2 January, 2006"
  favicon: "apple-touch-icon.png"
  feedlinks: true
  footer: "Powered by [Hugo](https://gohugo.io/) and the [Zen theme](https://github.com/frjo/hugo-theme-zen)."
  icon: "apple-touch-icon.png"
  image: "apple-touch-icon.png"
  imageMaxWidth: 
  logoWidth: 64
  mobileMenu: true
  poweredby: false
  realfavicongenerator: true
  sidebar: false
  submitted: true
  themecolor: "#794465"
