
* Introduction

This is the source of my personal website, based on hugo.

Visit my website at https://shreyas.ragavan.co

* Workflow

I use [[https://www.gnu.org/software/emacs/][Emacs]] for .. almost everything and use the excellent [[https://github.com/kaushalmodi/ox-hugo][ox-hugo]] package to
maintain the entire contents of my website in a single Org mode file. The
obvious advantage is the ability to work within Emacs, resulting in a friction
free writing and publishing experience.

This repository is pulled every 5 minutes through a cron job on my Linode VPS,
and the static website is served via Apache. The reason I use Apache instead of
the Hugo server, is that I also use the same VPS to serve multiple experimental
sites and wikis. Subsequent to the git pull, the Hugo server is started up to
build from this source repo and I've found it will only copy over updated or
modified files to the public directory served by Apache. Since Hugo generates
the entire site in milliseconds, I can get by with the cron job running every 5
minutes.

Anytime I want to create a blog post or an update, I work on a local hugo server
for previewing the post and the site, and once I commit and push - the cron job
described above will ensure the latest version of the site is deployed. I do not
edit any files of this site directly on the VPS.

It would actually be more efficient to use a service like Netlify for automated
deployment, which would add other benefits and make the process more
robust. That is.. for the future.

* Theme

Currently, this site uses the [[ https://github.com/frjo/hugo-theme-zen][Hugo Zen theme]], which I am modifying to make 'my
own'. The earlier theme was a modified version of a much older version of the
Hugo Academic theme. The main reason was to progressively reduce 'bloat' and
focus on a content centric design, and eventually reduce the page load and
Javascript to an absolute minimum.

No - I am more a hacker, both in skills and spirit and am not any kind of expert
in web design :) Constructive feedback is always welcome.
